
[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Store deploy time as environment variable
[context.production.environment]
  DEPLOY_TIME = "${DEPLOY_PRIME_PUBLISHED_AT}"
  COMMIT_REF = "${COMMIT_REF}"

# Also set for branch deploys
[context.branch-deploy.environment]
  DEPLOY_TIME = "${DEPLOY_PRIME_PUBLISHED_AT}"
  COMMIT_REF = "${COMMIT_REF}"
